language: python
script: "python ./runtests.py"
before_install:
    - sudo apt-get install swig
install:
    - "./m2crypto_ubuntu"
    - "pip install Django==$DJANGO"
    - "python setup.py install"
env:
    - DJANGO=1.3.7
    - DJANGO=1.4.5
    - DJANGO=1.5.1
    - DJANGO=1.6.2
python:
    - "2.6"
    - "2.7"
